// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlggajmzyjrwojzhidlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsZ2dham16eWpyd29qemhpZGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDU5MTYsImV4cCI6MjA2NjIyMTkxNn0.HSRXxseFiCnX5VpM51NjJ18sMJ3XNNKCnq_8hV1e_dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);